name: build-image
description: action for building images
inputs:
  VAR1:
    description: variable 1
    required: true
  VAR2:
    description: variable 2
    required: true
runs:
  using: "composite"
  steps:
    - run: |
          echo ${{ inputs.VAR1 }}
      shell: bash
    - run: |
          echo ${{ inputs.VAR2 }}
      shell: bash